# Generated by Django 2.0.2 on 2018-02-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180222_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
